version: "3"

services:

  api:
    build: .
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.12
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tab
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

    depends_on:
      - mongo